name: release

on:
  push:
    branches:
      - release/prd

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2

      - name: Getting the version...
        run: |
          var=$(tr --delete "\n" < version)
          echo "version=${var}" >> $GITHUB_ENV

      - name: Building...
        run: |
          go build -ldflags "-s -w -X main.version=${{ env.version }}"

      - name: Creating a Tag...
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "${{ env.version }}"

      - name: Creating a Release...
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./crock
          tag: "${{ env.version }}"
          token: ${{ secrets.PAT }}
