name: release

on:
  push:
    branches:
      - release/prd

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2

      - name: Getting the version...
        run: |
          var=$(tr --delete "\n" < version)
          echo "version=${var}" >> $GITHUB_ENV

      - name: Building...
        run: |
          mkdir ./linux
          mkdir ./mac
          mkdir ./windows
          GOOS=linux GOARCH=amd64 go build -o ./linux/crock -ldflags "-s -w -X main.version=${{ env.version }}"
          GOOS=darwin GOARCH=amd64 go build -o ./mac/crock -ldflags "-s -w -X main.version=${{ env.version }}"
          GOOS=windows GOARCH=amd64 go build -o ./windows/crock.exe -ldflags "-s -w -X main.version=${{ env.version }}"

      - name: Creating a Tag...
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "${{ env.version }}"

      - name: Creating a Release...
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./linux/crock, ./mac/crock, ./windows/crock.exe
          tag: "${{ env.version }}"
          token: ${{ secrets.PAT }}
